import { getAuthOrGuest } from '@/lib/auth-or-guest'
import { NextResponse } from 'next/server'

export const runtime = 'nodejs'

/**
 * POST /api/voice/tts
 * Convert text to speech using OpenAI TTS API.
 * Returns audio/mpeg blob.
 * Used for the welcome message which is generated by Claude (text only).
 */
export async function POST(request: Request) {
  const session = await getAuthOrGuest()
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) {
    return NextResponse.json({ error: 'OpenAI not configured' }, { status: 500 })
  }

  const { text, language } = await request.json() as { text?: string; language?: 'ES' | 'EN' }
  if (!text || typeof text !== 'string') {
    return NextResponse.json({ error: 'text required' }, { status: 400 })
  }
  const lang: 'ES' | 'EN' = language === 'EN' ? 'EN' : 'ES'

  // Limit text length to avoid abuse / huge audio files
  const trimmedText = text.slice(0, 4000)

  // Instrucciones de voz según idioma. shimmer soporta ambos nativos.
  // CONSISTENCIA: se pide entrega PAREJA (tono/volumen estables) porque el
  // audio se genera por partes y, sin esto, cada fragmento sale con pitch y
  // volumen distintos (se escuchan saltos entre frases).
  const voiceInstructions = lang === 'EN'
    ? 'Speak in clear, neutral American English. Warm, professional instructor tone — calm and even. Keep a STEADY pitch and a CONSTANT volume from start to finish; avoid abrupt changes in pitch, loudness or pace. Uniform, controlled delivery, never robotic. Pronounce technical terms clearly.'
    : 'Habla en español latinoamericano con acento peruano neutro. Tono cálido y profesional de instructora, calmado y parejo. Mantén un pitch ESTABLE y un volumen CONSTANTE de principio a fin; evita cambios bruscos de tono, intensidad o ritmo. Entrega uniforme y controlada, nunca robotizada. Pronuncia "z" y "ce/ci" como "s" (seseo). NUNCA uses acento de España.'

  try {
    const response = await fetch('https://api.openai.com/v1/audio/speech', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini-tts',
        voice: 'shimmer',
        input: trimmedText,
        instructions: voiceInstructions,
        response_format: 'mp3',
      }),
    })

    if (!response.ok) {
      const error = await response.text()
      console.error('OpenAI TTS error:', error)
      return NextResponse.json({ error: 'TTS failed' }, { status: 500 })
    }

    const audioBuffer = await response.arrayBuffer()
    return new Response(audioBuffer, {
      headers: {
        'Content-Type': 'audio/mpeg',
        'Cache-Control': 'no-cache',
      },
    })
  } catch (e) {
    console.error('TTS error:', e)
    return NextResponse.json({ error: 'TTS error' }, { status: 500 })
  }
}
